version: '3.7'

services:
  main:
    image: denden047/spatial_networks:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "../src:/work"
      - "../result:/result"
    working_dir: '/work'
